using Microsoft.EntityFrameworkCore.Migrations;
using System.IO;

//Put this in the first migration
//var seeder = new SeedData.SeedDataMigration();
//seeder.Seed(migrationBuilder);

namespace voidBitz.NETCore.NetCoreCountries.DataAccess.Migrations.SeedData
{
    public class SeedDataMigration 
    {
        public void Seed(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"INSERT INTO Country (ID, Name, Abbreviation) VALUES (1,'United States','US');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (3,'Canada','CA');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (4,'Afghanistan','AF');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (5,'Albania','AL');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (6,'Algeria','DZ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (8,'American Samoa','AS');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (9,'Andorra','AD');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (10,'Angola','AO');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (11,'Anguilla','AI');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (12,'Antigua and Barbuda','AG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (13,'Argentina','AR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (14,'Aruba','AW');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (15,'Australia','AU');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (17,'Austria','AT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (18,'Bahrain','BH');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (19,'Bahamas','BS');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (20,'Bangladesh','BD');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (21,'Barbados','BB');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (22,'Belgium','BE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (23,'Belize','BZ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (24,'Benin','BJ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (25,'Bermuda','BM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (26,'Bhutan','BT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (27,'Bolivia','BO');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (29,'Botswana','BW');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (30,'Brazil','BR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (32,'Brunei','BN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (33,'Bulgaria','BG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (34,'Burkina Faso','BF');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (35,'Myanmar (Burma)','MM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (36,'Burundi','BI');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (37,'Cayman Islands','KY');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (38,'Kampuchea (Cambodia)','KH');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (40,'Cameroon','CM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (41,'Cape Verde','CV');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (42,'Central African Republic','CF');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (43,'Sri Lanka (Ceylon)','LK');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (44,'Chad','TD');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (45,'Chile','CL');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (46,'China','CN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (48,'Taiwan (Formosa)','TW');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (49,'Cocos','CC');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (50,'Comoros','KM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (51,'Cook Islands','CK');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (52,'Colombia','CO');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (53,'Zaire (Formerly Congo)','CG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (54,'Congo','CG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (55,'Costa Rica','CR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (56,'Cuba','CU');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (59,'Cyprus','CY');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (60,'Czechoslovakia','CZ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (61,'Denmark','DK');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (62,'Dominica','DM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (63,'St Lucia','LC');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (64,'Djibouti','DJ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (65,'Dominican Republic','DO');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (66,'East Africa (Uganda)','UG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (68,'Ecuador','EC');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (69,'Egypt (choose United Arab Republic)','EG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (70,'El Salvador','SV');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (72,'Equatorial Guinea','GQ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (74,'Ethiopia','ET');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (75,'Falkland Islands','FK');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (76,'Fiji','FJ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (77,'Finland','FI');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (79,'French Guiana','GF');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (80,'French Polynesia','PF');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (81,'France','FR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (82,'Gabon','GA');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (83,'Gambia','GM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (84,'Germany','DE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (87,'Ghana','GH');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (88,'Gibraltar','GI');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (89,'Greece','GR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (90,'Greenland','GL');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (91,'Grenada','GD');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (92,'Guadeloupe','GP');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (93,'Guam','GU');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (94,'Guatemala','GT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (95,'Guinea','GN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (96,'Guinea-Bissau','GW');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (97,'Guyana','GY');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (98,'Haiti','HT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (99,'Honduras','HN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (100,'Hong Kong','HK');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (101,'Hungary','HU');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (102,'Iceland','IS');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (103,'India','IN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (105,'Indonesia','ID');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (106,'Iran','IR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (107,'Iraq','IQ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (108,'Ireland','IE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (109,'Israel','IL');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (110,'Italy','IT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (111,'Cote d'+char(39)+'Ivoire (Ivory Coast)','CI');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (112,'Jamaica','JM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (113,'Japan','JP');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (114,'Jordan','JO');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (115,'Kenya','KE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (116,'Kiribati','KI');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (117,'Korea-North','KP');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (118,'Korea-South','KR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (119,'Kuwait','KW');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (120,'Laos','LA');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (121,'Latvia (choose Commonwealth Ind States)','LV');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (122,'Lebanon','LB');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (123,'Lesotho','LS');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (124,'Liberia','LR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (125,'Libya','LY');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (126,'Liechtenstein','LI');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (127,'Lithuania  (choose Commonwealth Ind States)','LT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (128,'Luxembourg','LU');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (129,'Macau','MO');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (130,'Madagascar','MG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (132,'Malawi','MW');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (133,'Malaysia','MY');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (134,'Mali','ML');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (135,'Maldives','MV');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (136,'Malta','MT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (137,'Martinique','MQ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (138,'Marshall Island','MH');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (139,'Mauritania','MR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (140,'Mauritius','MU');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (141,'Mexico','MX');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (142,'Micronesia','FM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (143,'Monaco','MC');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (144,'Mongolia','MN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (145,'Montserrat','MS');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (146,'Morocco','MA');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (147,'Mozambique','MZ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (148,'Namibia','NA');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (150,'Netherlands','NL');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (151,'Nevis and St Kitts','KN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (152,'Netherlands Antilles','AN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (153,'New Caledonia','NC');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (154,'New Zealand','NZ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (155,'Nepal','NP');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (156,'Nauru','NR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (157,'Nicaragua','NI');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (158,'Niger','NE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (159,'Nigeria','NG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (160,'Northern Mariana Islands','MP');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (161,'Norway','NO');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (162,'Oman','OM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (164,'Pakistan','PK');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (165,'Panama','PA');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (166,'Papua New Guinea','PG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (167,'Paraguay','PY');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (168,'Palau','PW');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (169,'Peru','PE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (170,'Philippines','PH');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (171,'Pitcairn Islands','PN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (172,'Poland','PL');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (173,'Portugal','PT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (174,'Qatar','QA');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (175,'Reunion','RE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (176,'Zimbabwe (Rhodesia)','ZW');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (177,'Romania','RO');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (178,'Rwanda','RW');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (181,'San Marino','SM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (182,'Sao Tome and Principe','ST');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (183,'St Helena','SH');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (184,'St Vincent and Grenadines','VC');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (185,'Saudi Arabia','SA');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (186,'St Maarten','MF');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (187,'Scotland (choose UK, Scotland)','GB-SCT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (188,'Senegal','SN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (189,'Seychelles','SC');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (190,'Sierra Leone','SL');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (191,'Singapore','SG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (192,'Solomon Islands','SB');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (193,'Somalia','SO');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (194,'South Africa','ZA');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (195,'Spain','ES');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (196,'Sudan','SD');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (197,'Suriname','SR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (198,'Swaziland','SZ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (199,'Sweden','SE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (200,'Switzerland','CH');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (201,'Syria','SY');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (203,'Tanzania','TZ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (204,'Thailand','TH');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (205,'Tonga','TO');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (206,'Togo','TG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (207,'Trinidad and Tobago','TT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (208,'Tunisia','TN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (209,'Turkey','TR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (210,'Turks and Caicos Islands','TC');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (211,'Tuvalu','TV');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (212,'Uganda','UG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (213,'Commonwealth Ind States (USSR)','RU');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (214,'United Arab Emirates','AE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (215,'United Arab Republic (Egypt)','EG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (216,'UK (England-Wales)','GB-WLS');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (217,'UK (Northern Ireland)','GB-NIR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (218,'UK (Scotland)','GB-SCT');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (219,'Uruguay','UY');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (220,'Vanuatu','VU');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (221,'Venezuela','VE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (222,'Virgin Islands (US)','VI');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (223,'Virgin Islands (British)','VG');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (224,'Wallis and Futuna Islands','WF');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (225,'Western Sahara','EH');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (226,'Western Samoa','WS');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (227,'Vietnam','VN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (228,'Wales (choose UK, England-Wales)','GB-WLS');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (229,'Yemen','YE');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (231,'Zambia','ZM');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (234,'Croatia','HR');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (235,'Palestinian Authority','PS');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (236,'Russia (choose Commonwealth Ind States)','RU');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (237,'Azerbaijan','AZ');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (238,'Serbia','SRB');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (239,'Slovenia','SVN');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (240,'Bosnia and Herzegovina','BA');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (241,'Kosovo','KV');
                    INSERT INTO Country (ID, Name, Abbreviation) VALUES (242,'Macedonia','MKD');");
        }
    }
}
